### PR TITLE
fix: adapt for apatch installation

### PR DESCRIPTION
**Pull request by DataEraserC**

### CODE REVIEW

**Comment by DataEraserC** [comment]
https://github.com/3arthur6/BluetoothLibraryPatcher/issues/62

**Comment by DataEraserC** [comment]
I have no samsung device to test

**Comment by DataEraserC** [comment]
@egydoctor2010 may i ask u to test this?

**Comment by egydoctor2010** [comment]
Confirmed working sorry for late reply

**Comment by 3arthur6** [comment]
Thanks dudes!
Just added on latest release with @960bb08 commit

**Comment by 3arthur6** [comment]
Thanks dudes!
Just added on latest release with master@960bb08 commit

**Comment by 3arthur6** [comment]
Thanks dudes!
Just added on latest release with https://github.com/3arthur6/BluetoothLibraryPatcher/commit/960bb0849a0b0b74717f4b9b5757e364303c8d50 commit

**Comment by 3arthur6** [comment]
Thanks dudes!
Just added support in latest release with https://github.com/3arthur6/BluetoothLibraryPatcher/commit/960bb0849a0b0b74717f4b9b5757e364303c8d50 commit.

**Pull request closed without merging**
